image: repo.ima.io:8082/debian

variables: 
  url: "https://github.com/balena-os/balena-engine/releases/download/${tag}/balena-engine-${tag}-${arch}.tar.gz"
  tag: v17.12.0
  arch: armv7

stages: 
  - build 

build-stage1:   
  stage: build
  script:
    - apt-get update && apt-get install -y bash wget tar curl
    - mkdir -p ./archive/usr/bin
    - curl -sL "$url" | tar xzv -C ./archive/usr/bin --strip-components=1
    - wget http://ftp.de.debian.org/debian/pool/main/c/cgroupfs-mount/cgroupfs-mount_1.1_all.deb
    - dpkg-deb -x cgroupfs-mount_1.1_all.deb ./archive/
    - echo chown -R root:root ./archive/ >> ./archive/setup.sh
    - echo chmod -R 755 ./archive/ >> ./archive/setup.sh
    - echo cp -a ./archive/etc/. /etc/ >> ./archive/setup.sh
    - echo cp -a ./archive/usr/. /usr/ >> ./archive/setup.sh
    - echo groupadd docker >> ./archive/setup.sh
    - echo usermod -a -G docker admin >> ./archive/setup.sh
    - echo update-rc.d -s cgroupfs-mount defaults >> ./archive/setup.sh
    - echo update-rc.d -s balena defaults >> ./archive/setup.sh
    - wget https://github.com/megastep/makeself/releases/download/release-2.4.0/makeself-2.4.0.run
    - chmod +x makeself-2.4.0.run
    - ./makeself-2.4.0.run --target .
    - chmod +x create-archive.sh
    - ./create-archive.sh
  when: manual
  artifacts:
    paths:
      - build/
    expire_in: 1 week
